.TH yffs-chown 1
.SH NAME
yffs-chown \-   modify the owner of a file in the filesystem
.SH SYNOPSIS
.B yffs-chown
[ filesystem ] [ file ] [ user ] 
.SH DESCRIPTION
.I  yffs-owner
will access the owner variable of a file stored in the filesystem and update the user specified as the owner if permissions allow it.
.SH EXAMPLE
.TP
yffs-chown example hello.txt vlad 
changes the owner of hello.txt to the user with username vlad. No output is printed when the owner is successfully changed.
.SH "SEE ALSO"
yffs(1), yffs-add(1), yffs-cat(1), yffs-create(1), yffs-edit(1), yffs-ls(1), yffs-rm(1), yffs-chown(1)
.SH BUGS
Please report any yffs bugs to bvervaet@purdue.edu
.SH AUTHORS
Written by Wyatt Dahlenburg, Zach Kent, Max Molnar, Sam Spencer, and Brian VerVaet
.SH COPYRIGHT
Copyright \(co 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.